server:
  port: 18080
  servlet:
    context-path: /transaction
spring:
  application:
    name: xl-transaction
  datasource:
    url: jdbc:mysql://localhost:3306/fintech?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
