#其他配置数据在nacos里
spring:
  #Redis相关配置
  data:
    redis:
      host: 192.168.93.135
      port: 6379
      database: 0
      jedis:
        pool:
          max-active: 8 #最大连接数
          max-wait: 100ms #连接池最大阻塞等待时间
          max-idle: 4 #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接
  datasource:
    url: jdbc:mysql://localhost:3306/fintech_sp?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver