spring:
  datasource:
    url: jdbc:mysql://192.168.224.128:3306${xl.db}?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:  #Redis相关配置
      host: 192.168.224.128
      port: 6379
      database: 0
      jedis:
        pool:
          max-active: 8 #最大连接数
          max-wait: 100ms #连接池最大阻塞等待时间
          max-idle: 4 #连接池中的最大空闲连接
          min-idle: 0 #连接池中的最小空闲连接
      password: root
logging:  # spring框架的日志。日志配置 无特殊需求无需更改
  config: classpath:com/xl/common/log4j2.xml
#  pattern:
#    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    com.zaxxer.hikari: error
    com.alibaba: error
#    root: info
#    javax.activation: info
#    org.apache.catalina: info
#    org.apache.commons.beanutils.converters: info
#    org.apache.coyote.http11.Http11Processor: info
#    org.apache.http: info
#    org.apache.tomcat: info
#    org.springframework: debug
#    com.chinamobile.cmss.bdpaas.resource.monitor: debug
