spring:
#  main:
#    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot3.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
#    url: jdbc:mysql://192.168.224.128:3306/?useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
#      validationQuery: SELECT 1 FROM DUAL  # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      testWhileIdle: true   # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      testOnBorrow: false   # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      testOnReturn: false   # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      poolPreparedStatements: false    # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      maxPoolPreparedStatementPerConnectionSize: -1  # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      use-global-data-source-stat: true # 合并多个DruidDataSource的监控数据
      filters: stat,wall,slf4j  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      web-stat-filter:
        enabled: true   # 是否启用StatFilter默认值true
        url-pattern: /*   # 添加过滤规则
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico   # 忽略过滤的格式
      stat-view-servlet:
        enabled: true   # 是否启用StatViewServlet默认值true
        url-pattern: /druid/*   # 访问路径为/druid时，跳转到StatViewServlet
        reset-enable: true    # 是否能够重置数据
        login-username: druid   # 需要账号密码才能访问控制台，默认为root
        login-password: druid
        allow:  # IP白名单
#        deny:  # IP黑名单（共同存在时，deny优先于allow）
  shardingsphere:
    datasource:
      druid-common-config: &common   # 定义公共配置（锚点）
        druid:
        initial-size: 5  # 初始化时建立物理连接的个数
        min-idle: 3   # 连接池的最小空闲数量
        max-active: 20    # 连接池最大连接数量
        maxWait: 60000    # 配置获取连接等待超时的时间
        timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        minEvictableIdleTimeMillis: 300000   # 配置一个连接在池中最小生存的时间，单位是毫秒
#        filters: stat,wall
        stat-view-servlet:
          enabled: true
          login-username: druid
          login-password: druid
        web-stat-filter:
          enabled: true
          url-pattern: /*
          exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      names: ds_master_0,ds_slave_0
      ds_master_0:
        url: jdbc:mysql://192.168.224.128:3306/xl_users  #使用druid需要把jdbc-url改成url
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        <<: *common
      ds_slave_0:
        url: jdbc:mysql://192.168.224.128:3307/xl_users
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        <<: *common  # 引用公共配置
    rules:
      readwrite-splitting:  # Read-write separation
        data-sources:
          ds_master_0:
            static-strategy:
              write-data-source-name: ds_master_0
              read-data-source-names:
                - ds_slave_0
            load-balancer-name: round_robin
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
    props:  # Show SQL
      sql-show: true
