server:
  port: 28081
  servlet:
    context-path: /identitybusiness
spring:
  application:
    name: xl-identitybusiness # 服务名称
  config:
    import: classpath:application-common.yml    # 导入common模块的配置
#  cloud:
#    nacos:
#      server-addr: 192.168.93.135:8848 # 注册Nacos地址
#      config:
#        server-addr: 192.168.93.135:8848  # Nacos地址，可忽略
#      # file-extension: yaml # 配置文件后缀名
#      # ${spring.application.name}-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}`作为文件id，来读取配置。
#      discovery:
#        cluster-name: CS
#        namespace: be3c27a4-7d8a-4723-8de5-40e17ac2d4af # 命名空间，填ID
#2021.0.5版本的 Spring Cloud 默认不再启用 bootstrap包
#  config:
#    import:
#      - optional:nacos:fintech-service-identitybusiness.yaml?group=DEFAULT_GROUP&refreshEnabled=true
# dubbo注册地址
#dubbo:
#  protocol:
#    name: dubbo
#    port: 20880
#  registry:
#    address: nacos://192.168.93.135:8848
#    use-as-metadata-center: false #关闭dubbo自己在nacos创建配置
#  #    address: spring-cloud://localhost   #使用spring cloud中的注册中心
#  scan:
#    base-packages: com.fintech.service.identitybusiness.service
#  consumer:
#    check: false
#  application:   #Qos=Quality of Service，qos是Dubbo的在线运维命令，可以对服务进行动态的配置、控制及查询
#    qos-enable: false    #是否启动QoS
#    serialize-check-status: WARN
#    check-serializable: false
#    qos-port: 2222    #启动QoS绑定的端口
#    qos-accept-foreign-ip: false    #是否允许远程访问
#  provider:  # 重写dubbo ExceptionFilter并生效
#    filter: customExceptionFilter,-exception


